# -*- coding: utf-8 -*-
# Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
from enum import StrEnum


class GenerationStatus(StrEnum):
    SUCCESS = "success"
    DEGRADED = "degraded"
    UNSUPPORTED = "unsupported"
    FAILED = "failed"


class ErrorCode(StrEnum):
    UNKNOWN_CAPABILITY = "UNKNOWN_CAPABILITY"
    APP_VERSION_UNSUPPORTED = "APP_VERSION_UNSUPPORTED"
    PACKAGE_NOT_INSTALLED = "PACKAGE_NOT_INSTALLED"
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    WRITE_RESULT_CONFLICT = "WRITE_RESULT_CONFLICT"
    NO_EFFECTIVE_CAPABILITY = "NO_EFFECTIVE_CAPABILITY"
    PROTOCOL_CAPABILITY_UNSUPPORTED = "PROTOCOL_CAPABILITY_UNSUPPORTED"
    A2UI_GENERATION_FAILED = "A2UI_GENERATION_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    ARTIFACT_UPLOAD_FAILED = "ARTIFACT_UPLOAD_FAILED"
    WIDGET_EDIT_DISABLED = "WIDGET_EDIT_DISABLED"
    SOURCE_ARTIFACT_NOT_FOUND = "SOURCE_ARTIFACT_NOT_FOUND"
    SOURCE_ARTIFACT_DOWNLOAD_FAILED = "SOURCE_ARTIFACT_DOWNLOAD_FAILED"
    SOURCE_ARTIFACT_SCHEMA_UNSUPPORTED = "SOURCE_ARTIFACT_SCHEMA_UNSUPPORTED"
    SOURCE_ARTIFACT_INVALID = "SOURCE_ARTIFACT_INVALID"
    TIMEOUT = "TIMEOUT"
